---
apiVersion: v1
kind: Service
metadata:
  name: cns-gitclone-backend
  namespace: cns-test
spec:
  ports:
  - port: 9195
    protocol: TCP
    targetPort: 9195
    nodePort: 30169
  selector:
    app: cns-gitclone-backend
  type: LoadBalancer
#  type: ClusterIP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cns-gitclone-backend
  labels:
    app: cns-gitclone-backend
  namespace: cns-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cns-gitclone-backend
  template:
    metadata:
      labels:
        app: cns-gitclone-backend
    spec:
      containers:
      - name: cns-gitclone-backend
        image: farhan23432/cns-gitclone-backend:1655551011
        imagePullPolicy: Always
        ports:
        - containerPort: 9195
